title: Filo-Bayes
description: Un taller de filog√©netica bayesiana en RevBayes impartido en la UNAM, Enero 2025

theme: just-the-docs

url: https://ixchelgzlzr.github.io/filo_bayes_UNAM/

Template Repository: https://github.com/ixchelgzlzr/filo_bayes_UNAM

search_enabled: false

enable_copy_code_button: true

heading_anchors: true

back_to_top: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "./assets/img/logo_1.png" 

